### PR TITLE
[BUG] Fix fetch incorrect data chunk

### LINKED ISSUE #925: [BUG] Client might fetch incorrect chunk.
### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

### PR DESCRIPTION
**Pull request by FMX**
# [BUG]Fix fetch incorrect data chunk.

### What changes were proposed in this pull request?
If a client is failed, read the peer replica from its beginning.

### Why are the changes needed?
To prevent potential data loss.

### Related issues.
closes #925 

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

File: common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala [hunk 1]
```diff
@@ -2520,4 +2521,12 @@ object CelebornConf extends Logging {
       .doc("The time before a cache item is removed.")
       .timeConf(TimeUnit.MILLISECONDS)
       .createWithDefaultString("15s")
+
+  val FETCH_FAIL_TRIGGER: ConfigEntry[Int] =
```
Comment (waitinfuture) [inline common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala:2525]: Plz add docs describing this config

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 2]
```diff
@@ -149,13 +144,11 @@ public synchronized int openChunks() throws IOException {
...
-                "Could not open chunks from %s after %d tries.", currentReplica, numTries),
+            String.format("Could not open chunks from %s after %d tries.", replica, numTries),
             currentException);
       } else {
         throw new IOException(
-            String.format(
-                "Could not open chunks from %s after %d tries.", currentReplica, numTries));
+            String.format("Could not open chunks from %s after %d tries.", replica, numTries));
       }
     }
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:153]: We should set numTries to zero before return

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 3]
```diff
@@ -169,11 +162,20 @@ public synchronized int openChunks() throws IOException {
    * @param chunkIndex the index of the chunk to be fetched.
    */
   public void fetchChunk(int chunkIndex) {
-    Replica replica;
     RetryingChunkReceiveCallback callback;
     synchronized (this) {
-      replica = getCurrentReplica();
       callback = new RetryingChunkReceiveCallback(numTries);
+      if (location.getPeer() != null
+          && fetchFailTrigger != 0
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:169]: make fetchFailTrigger != 0 the first condition

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 4]
```diff
@@ -256,7 +252,7 @@ public void onFailure(int chunkIndex, Throwable e) {
         initiateRetry(chunkIndex, this.currentNumTries);
       } else {
         logger.error("Abandon to fetch chunk {} after {} tries.", chunkIndex, this.currentNumTries);
-        callback.onFailure(chunkIndex, e);
+        callback.onFailure(chunkIndex, new ChunkClientException(e.getMessage(), e, location));
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:255]: We should make location a parameter or onFailure instead of ChunkClientException

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 5]
```diff
@@ -75,24 +83,48 @@ public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
...
+                  client.set(
+                      new ChunkClient(
+                          conf,
+                          shuffleKey,
+                          location.getPeer(),
+                          this,
+                          clientFactory,
+                          startMapIndex,
+                          endMapIndex));
+                  currentChunkIndex.set(0);
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:104]: There can be concurrent issues when in-flight fetches return.

**Comment by waitinfuture** [comment]
I would like to cc @AngersZhuuuu to review if there are other potential concurrent issues

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java (hunk 5 above)
Comment (FMX) [reply client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:103]: Those variables "currentChunkIndex, returnedChunks, numChunks" are synced and atomic.

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java (hunk 2 above)
Comment (FMX) [reply client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:159]: done

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 6]
```diff
@@ -188,17 +194,11 @@ public void fetchChunk(int chunkIndex) {
       if (shouldRetry(e)) {
         initiateRetry(chunkIndex, callback.currentNumTries);
       } else {
-        callback.onFailure(chunkIndex, e);
+        callback.onFailure(chunkIndex, e, location);
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:197]: location should precede exception

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 7]
```diff
@@ -74,25 +82,54 @@ public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
...
-            logger.error(errorMsg, e);
-            exception.set(new IOException(errorMsg, e));
+          public void onFailure(int chunkIndex, Throwable e, PartitionLocation location) {
+            readableLocations.remove(location);
+            if (readableLocations.isEmpty()) {
+              String errorMsg = "Fetch chunk " + chunkIndex + " failed.";
+              logger.error(errorMsg, e);
+              exception.set(new IOException(errorMsg, e));
+            } else {
+              if (!readableLocations.contains(location)) {
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:92]: Seems this condition will always be true because readableLocations removes location first

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 8]
```diff
@@ -74,25 +82,54 @@ public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
...
-    return returnedChunks < numChunks;
+  public synchronized boolean hasNext() {
+    return returnedChunks.get() < numChunks.get();
   }
 
-  public ByteBuf next() throws IOException {
+  public synchronized ByteBuf next() throws IOException {
     checkException();
-    if (chunkIndex < numChunks) {
+    if (currentChunkIndex.get() < numChunks.get()) {
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:132]: There will be concurrent issue here. If results is empty and fetch chunk fail, it will set exception since this method is sync and on failure will wait

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 9]
```diff
@@ -74,26 +82,54 @@ public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
...
+                    client =
+                        new ChunkClient(
+                            conf,
+                            shuffleKey,
+                            location.getPeer(),
+                            this,
+                            clientFactory,
+                            startMapIndex,
+                            endMapIndex);
+                    currentChunkIndex = (0);
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:105]: remove braces

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 10]
```diff
@@ -74,26 +82,54 @@ public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
...
+                    returnedChunks = (0);
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:106]: ditto

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 11]
```diff
@@ -107,7 +143,9 @@ public ByteBuf next() throws IOException {
       exception.set(ioe);
       throw ioe;
     }
-    returnedChunks++;
+    synchronized (this) {
+      returnedChunks++;
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:147]: There can be concurrent issue here. The returned chunk might be from failed location.

**Comment by RexXiong** [comment]
+1

File: common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala [hunk 12]
```diff
@@ -2520,4 +2521,13 @@ object CelebornConf extends Logging {
...
+    buildConf("celeborn.test.client.fetch.fetchFailTrigger")
```
Comment (pan3793) [inline common/src/main/scala/org/apache/celeborn/common/CelebornConf.scala:2526]: The name is confusing, suggest 
- "celeborn.test.client.fetchFailedChuckIndex" or
- "celeborn.test.client.fetch.failedChuckIndex"

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 13]
```diff
@@ -137,4 +179,18 @@ private void checkException() throws IOException {
       throw e;
     }
   }
+
+  private class ChunkData {
```
Comment (pan3793) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:183]: could it be a static inner class?

**Comment by pan3793** [comment]
could you please add a little bit background about this issue?

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 14]
```diff
@@ -81,30 +87,22 @@ public RetryingChunkClient(
       int endMapIndex) {
     TransportConf transportConf =
         Utils.fromCelebornConf(conf, TransportModuleConstants.DATA_MODULE, 0);
-
+    this.fetchFailTrigger = conf.fetchFailTrigger();
```
Comment (pan3793) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:90]: the variable name should indicate it's only for testing purpose

File: client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java [hunk 15]
```diff
@@ -58,75 +62,113 @@ public class WorkerPartitionReader implements PartitionReader {
...
+          public void onFailure(int chunkIndex, PartitionLocation location, Throwable e) {
+            readableLocations.remove(location);
+            if (readableLocations.isEmpty()) {
+              String errorMsg = "Fetch chunk " + chunkIndex + " failed.";
+              logger.error(errorMsg, e);
+              exception.set(new IOException(errorMsg, e));
+            } else {
+              try {
+                synchronized (this) {
+                  if (!failedLocations.contains(location)) {
```
Comment (pan3793) [inline client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:92]: so this is the key point of this PR? to avoid try fetch PR on the excluded nodes?

Comment (FMX) [reply client/src/main/java/org/apache/celeborn/client/read/WorkerPartitionReader.java:92]: The key point of this PR is to fetch whole replica  if one replica is failed.

**Comment by zhongqiangczq** [comment]
+1

**Review by pan3793 — APPROVED** [review]

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 16]
```diff
@@ -115,29 +113,26 @@ public RetryingChunkClient(
    */
   public synchronized int openChunks() throws IOException {
     int numChunks = -1;
-    Replica currentReplica = null;
     Exception currentException = null;
     while (numChunks == -1 && hasRemainingRetries()) {
       // Only not wait for first request to each replicate.
-      currentReplica = getCurrentReplica();
-      if (numTries >= replicas.length) {
+      if (numTries >= maxTries) {
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:119]: This condition will always be false, see hasRemainingRetries

File: client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java [hunk 17]
```diff
@@ -246,17 +246,17 @@ private class RetryingChunkReceiveCallback implements ChunkReceivedCallback {
     }
 
     @Override
-    public void onSuccess(int chunkIndex, ManagedBuffer buffer) {
-      callback.onSuccess(chunkIndex, buffer);
+    public void onSuccess(int chunkIndex, ManagedBuffer buffer, PartitionLocation location) {
+      callback.onSuccess(chunkIndex, buffer, ChunkClient.this.location);
```
Comment (waitinfuture) [inline client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:250]: It's wired that when RetryingChunkReceiveCallback.onSuccess is called in TransportResponseHandler, null is passed as location. I think it's not a good idea to make RetryingChunkReceiveCallback a subclass of ChunkReceivedCallback, just make callback and location a class member of RetryingChunkReceiveCallback. TransportResponseHandler's outstandingFetches be type of RetryingChunkReceiveCallback, and make RetryingChunkReceiveCallback public.

Comment (waitinfuture) [reply client/src/main/java/org/apache/celeborn/client/read/ChunkClient.java:250]: We can do this in later pr

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!
