### PR TITLE
[ISSUE-863][BUG]LifecycleManager should ignore change partition request when shuffle ended and not remove workersnapshot when commit success

### LINKED ISSUE #863: [BUG]LifecycleManager should ignore change partition request when shuffle ended and not remove workersnapshot when commit success
### What is the bug(with logs or screenshots)?
```
22/10/25 15:09:21,828 DEBUG [dispatcher-event-loop-14] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:09:21,828 INFO [dispatcher-event-loop-14] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]
22/10/25 15:25:27,728 DEBUG [dispatcher-event-loop-43] Worker: Received CommitFiles request, application_1665646136650_2510409_1-33, master files 64-1,833-0,1345-1,164-1,584-2,1161-1,1129-2,1131-0,237-0,818-1,819-1,1429-0,535-0,733-1,478-1; slave files 832-0,672-1,130-1,134-1,1130-0,1034-1,236-0,268-1,883-1,1428-0,564-1,534-0,508-1,221-1.
22/10/25 15:25:31,807 DEBUG [dispatcher-event-loop-32] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:25:32,130 INFO [dispatcher-event-loop-32] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]
22/10/25 15:09:21 WARN LifecycleManager: Batch handle change partition for application_1665646136650_2510409_1 of [33-478-0]
22/10/25 15:09:21 INFO LifecycleManager: Reserve buffer success for application_1665646136650_2510409_1-33
22/10/25 15:09:21 WARN LifecycleManager: Renew 33 [(478 0 -> 1)]  success.
22/10/25 15:25:31 INFO LifecycleManager: Succeed to handle stageEnd for 33.
22/10/25 15:25:31 WARN LifecycleManager: New partition not found, old partition 33 478-0
22/10/25 15:25:31 WARN LifecycleManager: Batch handle change partition for application_1665646136650_2510409_1 of [33-478-0]
22/10/25 15:25:31 WARN LifecycleManager: Renew 33 []  success. 
```

### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?

33-478-1 create file twice

Worker
```
22/10/25 15:09:21,828 DEBUG [dispatcher-event-loop-14] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:09:21,828 INFO [dispatcher-event-loop-14] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]
22/10/25 15:25:27,728 DEBUG [dispatcher-event-loop-43] Worker: Received CommitFiles request, application_1665646136650_2510409_1-33, master files 64-1,833-0,1345-1,164-1,584-2,1161-1,1129-2,1131-0,237-0,818-1,819-1,1429-0,535-0,733-1,478-1; slave files 832-0,672-1,130-1,134-1,1130-0,1034-1,236-0,268-1,883-1,1428-0,564-1,534-0,508-1,221-1.
22/10/25 15:25:31,807 DEBUG [dispatcher-event-loop-32] Worker: Received ReserveSlots request, application_1665646136650_2510409_1-33, master partitions: 478-1; slave partitions: .
22/10/25 15:25:32,130 INFO [dispatcher-event-loop-32] Worker: Reserved 1 master location and 0 slave location for application_1665646136650_2510409_1-33 master: [PartitionLocation[478-1 10.130.86.41:9092:9094:9093:9095 Mode: Master peer: 10.130.75.25:9092:9094:9093storage hint:MEMORY]]

```
LifecycleManager
```
22/10/25 15:09:21 WARN LifecycleManager: Batch handle change partition for application_1665646136650_2510409_1 of [33-478-0]
22/10/25 15:09:21 INFO LifecycleManager: Reserve buffer success for application_1665646136650_2510409_1-33
22/10/25 15:09:21 WARN LifecycleManager: Renew 33 [(478 0 -> 1)]  success.
22/10/25 15:25:31 INFO LifecycleManager: Succeed to handle stageEnd for 33.
22/10/25 15:25:31 WARN LifecycleManager: New partition not found, old partition 33 478-0
22/10/25 15:25:31 WARN LifecycleManager: Batch handle change partition for application_1665646136650_2510409_1 of [33-478-0]
22/10/25 15:25:31 WARN LifecycleManager: Renew 33 []  success. 
```

### Related issues.
close #863

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @waitinfuture @FMX

File: client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala [hunk 1]
```diff
@@ -586,6 +586,17 @@ class LifecycleManager(appId: String, val conf: CelebornConf) extends RpcEndpoin
       oldEpoch: Int,
       oldPartition: PartitionLocation,
       cause: Option[StatusCode] = None): Unit = {
+    if (!registeredShuffle.contains(shuffleId)) {
```
Comment (waitinfuture) [inline client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala:589]: I think we should move these checks inside reallocateChangePartitionRequestSlotsFromCandidates, because after that point the ReserveSlots will be called.

Comment (AngersZhuuuu) [reply client/src/main/scala/org/apache/celeborn/client/LifecycleManager.scala]: > I think we should move these checks inside reallocateChangePartitionRequestSlotsFromCandidates, because after that point the ReserveSlots will be called.

Then it can work for batch handling too. Nice suggestion, but how about the current? Moving this part inside `reallocateChangePartitionRequestSlotsFromCandidates` is a little strange, how about current?

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!
